### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by huseynovramil** [joaofbantunes/AspNetCoreRazorPagesInnerModelLocalizationSample#1]
It keeps showing "**Test**" instead of "**A test string**"

**Comment by joaofbantunes** [comment]
Hello!
Just tested from a clean clone plus `dotnet run`, it worked as expected:

<img width="760" alt="Screenshot 2019-03-24 at 10 16 43" src="https://user-images.githubusercontent.com/3763454/54877999-18964f00-4e1e-11e9-91a1-06201350bb59.png">
<img width="760" alt="Screenshot 2019-03-24 at 10 16 59" src="https://user-images.githubusercontent.com/3763454/54878000-18964f00-4e1e-11e9-9c68-b9935c15547e.png">

**Comment by joaofbantunes** [comment]
From the top of my mind, can't think of a good reason for it to work for me but not for you 😐

**Comment by huseynovramil** [comment]
Thanks man, it worked, the problem was that in Windows maximum path length is 260 chars and your folder name is too long, i just changed the name to shorter one

**Comment by joaofbantunes** [comment]
Oh, had that problem once as well (in a different project).
Should create a list of most common f$#& ups and put that one on the top of the list 😛
Glad you were able to figure it out 👍
